==== Prototype Pattern

Prototype (prototip) tasarım deseni creational grubununa ait, var olan nesnelerin kopyasının üretiminden sorumlu tasarım desenidir. 

Bazı nesnelerin üretilme maliyeti oldukça yüksek olabilir veya aynı değerlerde nesne üretilmesi gereken durumlar olabilir. Böyle nesnelerin üretim maliyetini azaltmak için var olan nesnenin kopyasının üretilmesi yoluna gidilebilir. Prototype tasarım deseni böyle durumdaki nesnelerin yönetilmesini sağlar.

İki farklı kopyalama şekli:

----
* Deep Copy (Derin Kopyalama)
* Shallow Copy (Yüzeysel Kopyalama)
----


Prototype tasarım deseninde 3 nesne yapısı vardır.

* Prototype: Klonlama yapılacak sınıfların uygulaması gereken interface veya abstract sınıf.
* Concrete Prototype: Klonlama özelliği olacak gerçek sınıflar.
* Client: Klonlanmış nesneyi elde edecek nesne.

Random rapidly tree(RRT)  kullanarak yapılacak olan yol planlaması projesinde prototype pattern haritaya sonradan nesne ekleme ( offline olarak) işlemlerinde kulalnılmıştır.

[source,C++]
----
#ifndef INCLUDE_TURTLEBOT_RRT_TURTLEBOT_RRT_H_
#define INCLUDE_TURTLEBOT_RRT_TURTLEBOT_RRT_H_

/** ROS kutuphanesi  **/
#include <ros/ros.h>

#include <move_base_msgs/MoveBaseAction.h>
#include <pluginlib/class_list_macros.h>
/** gloabal yol planlayıcı arayüzü için **/
#include <costmap_2d/costmap_2d_ros.h>
#include <costmap_2d/costmap_2d.h>
#include <nav_core/base_global_planner.h>
#include <geometry_msgs/PoseStamped.h>
#include <angles/angles.h>
#include <base_local_planner/world_model.h>
#include <base_local_planner/costmap_model.h>

/** standart kutuphaneler **/
#include <iostream>
#include <cmath>
#include <set>
#include <string>
#include <vector>
#include <utility>
#include <boost/random.hpp>
#include "vertex.h"

namespace turtlebot_rrt 
{
	class RTTplanner : public nav_core::BaseGlobalPlanner // nav_core::BaseGlobalPlanner arayüzünden türemiş bir sınıf
	{
	public:
		RRTPlanner(); // RRTPlanner için Yapıcı fonksiyon

		/*  constructor fonksiyon
		    name: düğüme ilişkilendirilecek isim
			costmap_ros: cost_map ros wrapper ı
		*/
		RRTPlanner(std::string name, costmap_2d::Costmap2DROS* costmap_ros);		
		void initialize(std::string name, costmap_2d::Costmap2DROS* costmap_ros); //*Ros handle ı başlat 
		/*
		   start: balangic konumu
		   goal: hedef
		   plan: yapılan yol planı
		*/
		bool makePlan(const geometry_msgs::PoseStamped& start, const geometry_msgs::PoseStamped& goal,
			std::vector<geometry_msgs::PoseStamped>& plan);
		/*
			engel haritasını döndürür
			std :: vector <bool> Güvenli olmayan hücreler false, güvenli hücreler true
		*/
		std::vector<bool> getObstacleMap(){ return obstacle_map_;}
		/*
			rrt vertex ağacını döndürür
		*/
		std::vector<turtlebot_rrt::Vertex> getVertexTree() 
		{
			return vertex_list_;
		}
		/*
			Harita alanında rastgele bir nokta alır
			x, y çifti döndürür
		*/
		std::pair<float, float> GetRandomPoint();
		int GetClosestVertex(std::pair<float, float> random_point);
		void addVertex(turtlebot_rrt::Vertex new_vertex) {
			vertex_list_.push_back(new_vertex);
		}
		float GetDistance(std::pair<float, float> start_point,
			std::pair<float, float> end_point);
		bool MoveTowardsPoint(int closest_vertex,
			std::pair<float, float> random_point);
		bool ReachedGoal(int new_vertex);
		std::vector<geometry_msgs::PoseStamped>
			BuildPlan(int goal_index,
				const geometry_msgs::PoseStamped& start,
				const geometry_msgs::PoseStamped& goal);
		int FindPath(const geometry_msgs::PoseStamped& start,
			const geometry_msgs::PoseStamped& goal);
		bool IsSafe(std::pair<float, float> start_point,
			std::pair<float, float> end_point);
		std::vector<pair<float, float>> obstacles;
	};
	//Prototype pattern icin:
	int main()
	{
		//random sayı üreticileri
		std::random_device rd;
		std::mt19937 gen(rd());
		std::pair<float, float> random_point;
		RTTplanner *prototype = new RTTplanner();
		costmap_2d::Costmap2D* costmap_;
		planner_1.initialize("First Planner", costmap_); // parametre olarak isim ve haritayı alan constructor çağırılır.
		RTTplanner *planner_1 = new RTTplanner(*prototype); //Deep copy (Referansı ile birlikte yapılır nesnenin tüm bilgileri kopyalanır)
		prototype->getObstacleMap(); 
		//rastgele bir noktaya engel eklenirse
		//problemin aslında engelin sınırlarının da veirlmesi gereklidir ancak basitçe örneklemek için rastgele(x,y) çifti kullanılmıştır.
		//std::uniform_real_distribution<> x(-map_width, map_width);
		//std::uniform_real_distribution<> y(-map_height, map_height);
		//haritanın sınırları verilmesi gerkiyor ancak projenin şu aşamasında henüz harita oluşturulamadıgı icin rastgele sayilar verilmistir
		std::uniform_real_distribution<> x(-10, 10);
		std::uniform_real_distribution<> y(-5, 5);
		random_point.first = x(gen);
		random_point.second = y(gen);
		planner_1->obstacles.push_back(random_point);// random bir koordinat
		RTTplanner *planner_2 = new RTTplanner();
		planner_2 = prototype;// shallow copy 
		planner_2->getObstacleMap;
		prototype->getObstacleMap;
	}
}
----


